name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Install dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      - name: Wait for MongoDB to be ready
        run: sleep 10

      - name: Verify MongoDB connection
        run: |
          echo "Testing MongoDB connection..."
          mongo --eval 'db.runCommand({ ping: 1 })'

      - name: Run backend integration tests
        working-directory: ./backend
        run: npm run test:integration
